build: cria_fila.c encerra_fila.c escreve_fila_assinc.c le_fila_assinc.c comunica_fila.h
	gcc cria_fila.c -o cria_fila -lrt
	gcc encerra_fila.c -o encerra_fila -lrt
	gcc escreve_fila_assinc.c -o escreve_fila_assinc -lrt
	gcc le_fila_assinc.c -o le_fila_assinc -lrt

clean:
	rm -f le_fila_assinc escreve_fila_assinc cria_fila encerra_fila